version: '3'

services:
  app:
    build: ./docker/go
    container_name: app
    tty: true
    volumes:
      - ./app:/go/src
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app

volumes:
  mysql_data:
